# Pare iOS - XcodeGen Project Specification
# Generates Pare.xcodeproj deterministically
# Run: ./Scripts/gen_xcode.sh

name: Pare

options:
  bundleIdPrefix: com.OptimusCashLLC
  deploymentTarget:
    iOS: "16.0"
  developmentLanguage: en
  xcodeVersion: "15.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true

settings:
  base:
    PRODUCT_NAME: Pare
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1,2"  # iPhone + iPad
    IPHONEOS_DEPLOYMENT_TARGET: "16.0"
    ENABLE_BITCODE: NO
    ENABLE_PREVIEWS: YES

configs:
  Debug: debug
  Release: release

configFiles:
  Debug: Config/Debug.xcconfig
  Release: Config/Release.xcconfig

targets:
  Pare:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    
    sources:
      - path: Pare
        excludes:
          - "**/.DS_Store"
    
    resources:
      - Pare/Resources/Assets.xcassets
      - Pare/Preview Content
    
    info:
      path: Pare/Resources/Info.plist
      properties:
        CFBundleDisplayName: Pare
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        LSRequiresIPhoneOS: true
        UILaunchStoryboardName: LaunchScreen
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.OptimusCashLLC.pare
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        SWIFT_EMIT_LOC_STRINGS: YES
        DEVELOPMENT_ASSET_PATHS: "\"Pare/Preview Content\""

schemes:
  Pare-Debug:
    build:
      targets:
        Pare: all
    run:
      config: Debug
      commandLineArguments:
        "-com.apple.CoreData.SQLDebug": "1"
    test:
      config: Debug
    profile:
      config: Debug
    analyze:
      config: Debug
    archive:
      config: Debug
      
  Pare-Release:
    build:
      targets:
        Pare: all
    run:
      config: Release
    test:
      config: Release
    profile:
      config: Release
    analyze:
      config: Release
    archive:
      config: Release

